### ISSUE TITLE
unable to properly install fenapack with anaconda

### ISSUE THREAD

**Issue by sblauth** [blechta/fenapack#9] opened 2018-11-30 12:05 UTC
Hello,

I have a problem when installing fenapack. I installed the 2018.1.0 version of it as described here. However, when I try to run the navier-stokes demo, I get the following error message: 

ImportError: generic_type: type "StabilizationParameterSD" referenced unknown base type "dolfin::Expression"

I have installed fenics through anaconda (also version 2018.1.0) and I am not sure how to fix it, or whether this could be anaconda related...
Thanks for your help

**Comment by blechta** [comment] 2018-12-03 15:23
Looks like broken installation of FEniCS and/or pybind11. Can you run https://bitbucket.org/fenics-project/dolfin/src/2018.1.0.post2/python/demo/documented/tensor-weighted-poisson/? If not, I recommend to ask at `#installation` channel of FEniCS Slack, you can ping me (username `@jan`).

**Comment by nschloe** [comment] 2019-12-20 15:01
Would have loved to see the discussion here! (I bumped into the same error, not with fenapack though.)

**Comment by blechta** [comment] 2020-01-08 11:14
@nschloe You might want to check the links mentioned in 51c9c62c56 and the discussion therein. I believe that the issue was related to https://github.com/pybind/pybind11/issues/633 and/or https://github.com/pybind/pybind11/issues/877.

**Comment by blechta** [comment] 2020-01-08 11:19
@plugged09 I would close the issue for now but feel free to reopen if the issue persists, ideally providing details how to reproduce the problem.

**Closed as completed by blechta** 2020-01-08 11:19 UTC
